name: multi_split_view
description: Provides horizontal or vertical multiple split view for Flutter.
version: 3.6.1-rc.2
repository: https://github.com/caduandrade/multi_split_view

screenshots:
  - description: Horizontal and vertical example
    path: screenshots/horizontal_vertical.png
  - description: Horizontal example
    path: screenshots/horizontal.png
  - description: Vertical example
    path: screenshots/vertical.png

topics:
  - split
  - widget
  - layout
  - area

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0